# Generated by Django 5.2.7 on 2025-10-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transparency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contribution',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorentity',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expenditure',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iecommittee',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='race',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
